### PR TITLE
Update dependencies for Symfony 3

### PR DESCRIPTION
**Pull request by bjornpost**
This updates the deps from `~2.7` to `~3.0`.

### CODE REVIEW

**Comment by bjornpost** [comment]
Travis fails because Symfony 3 no longer supports PHP 5.3 and 5.4.

**Comment by umpirsky** [comment]
@bjornpost Feel free to bump PHP version in both `composer.json` and `travis.yml`. Thanks. :+1:

**Comment by bjornpost** [comment]
@umpirsky Done :-)

**Comment by umpirsky** [comment]
Great job. Thanks @bjornpost! :+1:

**Pull request merged**
